### ISSUE TITLE
The Kezan

### ISSUE THREAD

**Issue by Ramys** [MoPSource/MopCore547#20]
Npcs are invisible in kezan in missions.
Only in Gm mode that sees them.

**Comment by Ramys** [comment]
Abandoned project?

**Comment by Keital** [comment]
No, just busy, we ha ve a real life you know?

**Comment by cooler-SAI** [comment]
I'll fix this zone later...

**Comment by alexkulya** [comment]
Пока проблема не решена, лучше пусть запрос останется открытым.

**Comment by cooler-SAI** [comment]
так он в ToDo записан

**Comment by cooler-SAI** [comment]
fixed
