### ISSUE TITLE
Quest Charge Buged

### ISSUE THREAD

**Issue by Dieguitox87** [MoPSource/MopCore547#63]
Quest ID: 14266

It should show complete when you charge the NPC. Doesnt happen

**Comment by Mysterium** [comment]
Tested, it works.
You are attacking the training dummy?

**Comment by Dieguitox87** [comment]
Nop. Its this quest http://www.wowhead.com/quest=14266/charge

**Comment by Mysterium** [comment]
My fault, tested it with human, not worgen.

It's now fixxed.
