### ISSUE TITLE
Quest Last Stand Buged

### ISSUE THREAD

**Issue by Dieguitox87** [MoPSource/MopCore547#67]
**Quest ID**: 14222
**Description:**
Cant complete quest Last Stand

**Current behaviour:**
When you pick up the quest there should appear some npc to kill and complete the quest

**Expected behaviour:**
When you pick up the quest you should see after NPC to kill and complete

**Steps to reproduce the problem:**

1. Create Worgen PJ
2. Pick up quest Last Stand
3. See there are no NPC (Just when you turn GM on they appear)

Wowhead: http://www.wowhead.com/quest=14222/last-stand

**Comment by Mysterium** [comment]
https://youtu.be/F78xlcks6es

Maybe you are in the wrong phase?

After the cannon quest, i run to him, accept quest and i see them, without .gm on
