### ISSUE TITLE
Compile erros

### ISSUE THREAD

**Issue by gasabi** [MoPSource/MopCore547#86]
/usr/bin/ld: CMakeFiles/authserver.dir/Server/RealmSocket.cpp.o: undefined reference to symbol 'pthread_condattr_setpshared@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
src/server/authserver/CMakeFiles/authserver.dir/build.make:240: recipe for target 'src/server/authserver/authserver' failed
make[2]: *** [src/server/authserver/authserver] Error 1
CMakeFiles/Makefile2:846: recipe for target 'src/server/authserver/CMakeFiles/authserver.dir/all' failed
make[1]: *** [src/server/authserver/CMakeFiles/authserver.dir/all] Error 2
make[1]: ** Esperando que outros processos terminem.

/usr/bin/ld: cannot find -lvalgrind
collect2: error: ld returned 1 exit status
src/server/worldserver/CMakeFiles/worldserver.dir/build.make:274: recipe for target 'src/server/worldserver/worldserver' failed
make[2]: *** [src/server/worldserver/worldserver] Error 1
CMakeFiles/Makefile2:1000: recipe for target 'src/server/worldserver/CMakeFiles/worldserver.dir/all' failed
make[1]: *** [src/server/worldserver/CMakeFiles/worldserver.dir/all] Error 2
Makefile:117: recipe for target 'all' failed

**Comment by Mysterium** [comment]
No linux supported yet.

**Comment by gasabi** [comment]
lol :(
