### ISSUE TITLE
Players are disconnected when entering to play

### ISSUE THREAD

**Issue by d3athbl0w** [MoPSource/MopCore547#89]
When players enter, they are disconnected immediately, The firewall is disabled, the ip is dynamic.

Have all database updates & core updates.

¿What do you think it is?

**Comment by alexkulya** [comment]
Disconnecting absolutely all players who try to come to the server?

P.S. They should come in with wow.exe file attached to the server.

If everything is observed, try to solve the problem with dynamic IP, the test was carried out, there were no problems with disconnections. Tested on a static IP.

**Comment by d3athbl0w** [comment]
It was a problem with my dynamic ip.

static ip working.

I'm sorry to have reported this stupid issue.

Thanks for your support, Close this issue.

**Comment by alexkulya** [comment]
Solved.
