### ISSUE TITLE
Compile error in visual studio 2015

### ISSUE THREAD

**Issue by d3athbl0w** [MoPSource/MopCore547#91]
Compile error with boss_zuljin.cpp

![28080588_1965912893437133_1658360467_o](https://user-images.githubusercontent.com/14060040/36272288-7651995a-1257-11e8-9d7f-b92f6a7462fe.png)

**Comment by wlasser** [comment]
possible to add in zulaman.h 
#define DATA_ZULJINEVENT    6

**Comment by cooler-SAI** [comment]
use VS 2013
